---
- name: restart opendkim
  service: name=opendkim state=restarted

- name: restart postfix
  service: name=postfix state=restarted

- name: create sasl_passwd.db
  shell: postmap hash:/etc/postfix/sasl_passwd
